# Generated by Django 5.2.5 on 2025-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'EN_COURS'), ('RENDU', 'RENDU')], default='EN_COURS', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='emprunt',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_COURS')), fields=('livre_id',), name='uniq_emprunt_en_cours_par_livre'),
        ),
    ]
